
---
# Author : Kishor Kumar Jha , Associate Principal SA ,Red Hat
- name: Example playbook to ensure Identified legacy services are disabled
  hosts: all
  tasks:
    - name: Disable the services
      service:
      name: "{{ item }}"
      enabled: no
      with_items:
    - named

    - name: Disable sockets
      shell: systemctl disable "{{ item }}"
      with_items:
      - telnet.socket
      - tftp.socke
      - dhcpd.socket
